"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Person_1 = require("./Person");
var Student_1 = require("./Student");
// var person1 = new Person();
// person1.id = 1;
// person1.name = "daonq1";
// person1.address = "HN";
var person1 = new Person_1.default(1, "daonq1", "HN");
// var person2 = new Person();
// person2.id = 2;
// person2.name = "daonq2";
// person2.address = "ND";
var person2 = new Person_1.default(2, "daonq2", "NĐ");
//
// var person3 = new Person();
console.log("Thông tin của person1: ");
console.log("ID: ", person1.getId());
console.log("Name: ", person1.getName());
console.log("Address: ", person1.getAddress());
console.log("--------------------------------");
console.log("Thông tin của person2: ");
console.log("ID: ", person2.getId());
console.log("Name: ", person2.getName());
console.log("Address: ", person2.getAddress());
console.log("Sử dụng hàm sayInfo");
person1.sayInfo();
person2.sayInfo();
console.log("--------------------------------");
var student1 = new Student_1.Student(1, "Student1", "HN", "Railway90", 9);
var student2 = new Student_1.Student(2, "Student2", "NĐ", "Railway90", 8);
student1.sayInfoStudent();
student2.sayInfoStudent();
